### ISSUE TITLE
undefined symbol: sampgdk_AddPlayerClass

### ISSUE THREAD

**Issue by SirFulgeruL** [grasmanek94/GPB#4]
Hello , 
I am trying to use AntiCheat.So and I get this error :
`./samp03svr: symbol lookup error: plugins/AntiCheat.so: undefined symbol: sampgdk_AddPlayerClass`
I added the libs from sampgdk latest version but stil doesn't work . 
In the server_log i dont have anything just the error above in the console.

**Comment by grasmanek94** [comment]
recompile anticheat with sampgdk you are using
