### ISSUE TITLE
Is there a variable for admins for bypass?

### ISSUE THREAD

**Issue by SirFulgeruL** [grasmanek94/GPB#5]
Hello there , 
is there a variable that the anticheat can detect , if it is an admin he will get a bypass

**Comment by grasmanek94** [comment]
You can check that yourself in `AC_OnCheatDetected(playerid, type, extraint, Float:extrafloat)` in your script(s), if player is admin just do nothing.

**Comment by SirFulgeruL** [comment]
Great thanks , I could use that for other things like if the server teleports him so it doesn't detect he is using teleport hack and so on ?

**Comment by grasmanek94** [comment]
antiCheat should be able to detect that your server teleported a player,
nonetheless, I never kicked players - always issued a warning to online
admins. and if no admins were online - if multiple cheats are detected +
someone starts a votekick only 33% of votes are required to kick the
offender (I preffer to not show how many votes are required, keep the
yes/no count hidden, and %, so everyone can make their own choice without
being affected by current results [going with the masses[).

**Comment by SirFulgeruL** [comment]
Ok thank you very much for you answer . 
First when I saw your topic on SA:MP I thought , it's too good to be true , and it really does the job . Thank you again .

**Comment by grasmanek94** [comment]
If you ever need a more up-to-date version of the AntiCheat and you have
C++ programming knowledge, here are some files used in my last server
(improved AC and protections, protections probably not working anymore on
newest SA-MP SVR version):

https://github.com/grasmanek94/eXe/blob/master/src/gamemode/AntiS0beit.cxx
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/AntiCheat.cxx
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/AntiCheat.hxx
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/CheatReportHandler.cxx
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/GetPacket.cxx
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/vehiclespeedlist.var

**Comment by SirFulgeruL** [comment]
I tried to think how i possibly could add the variable in the command , could you add it for me so I know how th command works ? Thanks .

`CMD:gotols(playerid, params[])
{
 if(gPlayerLogged[playerid] == 0) return SendClientMessage(playerid, COLOR_LIGHTRED, "You need to login first.");
 if(IsPlayerConnected(playerid))
 {
  if(PlayerInfo[playerid][pAdmin] >= 3)
  {
   new string[100],sendername[30];
   if (GetPlayerState(playerid) == 2)
   {
    new tmpcar = GetPlayerVehicleID(playerid);
    SetVehiclePos(tmpcar, 1529.6,-1691.2,13.3);
    TelePos[playerid][0] = 0.0;TelePos[playerid][1] = 0.0;
   }
   else
   {
    SetPlayerPosEx(playerid, 1529.6,-1691.2,13.3);
   }
   SendClientMessage(playerid, COLOR_GRAD1, "You have been teleported.");
   SetPlayerInterior(playerid,0);
   PlayerInfo[playerid][pInt] = 0;
   GetPlayerName(playerid, sendername, sizeof(sendername));
   format(string, sizeof(string), "Warning: Admin %s Teleported to LS.", sendername);
   Adminlog(string);
   if(InHouse[playerid] > -1)
   {
    StopAudioStreamForPlayer(playerid);
   }
   InHQ[playerid] = -1;
   InHouse[playerid] = -1;
   InBussines[playerid] = -1;
   SetPlayerVirtualWorld(playerid,0);
   if(GetPlayerState(playerid) == 2) ACInfo[playerid][acKicked] = 2;
   else ACInfo[playerid][acKicked] = 1;
  }
  else
  {
   SendClientMessage(playerid, COLOR_ERROR, AdminOnly);
  }
 }
 return 1;
}`

**Comment by SirFulgeruL** [comment]
I tried to think how i possibly could add the variable in the command , could you add it for me so I know how th command works ? Thanks .

Tried to add the command in here but it doesn't take the tabs ..
http://pastebin.com/pDaWvCbG

**Comment by SirFulgeruL** [comment]
Sorry for double-posting but could u do that for me please? 
I really need an anti-cheat for my server xD.

**Comment by grasmanek94** [comment]
I'm very bussy, I can't be anyones' personal coder. nope. And it's not that
hard, you can do it by yourself (surely you scripted your server so...).

**Comment by SirFulgeruL** [comment]
Yeah but the thing is I don't know how I could add that in my command .
So it takes it as a bypass.

**Comment by SirFulgeruL** [comment]
Hey , sorry for disturing you again , but I still don't get it how I could add the function into a command or something so that admins have a bypass.

**Comment by grasmanek94** [comment]
Well, if you lack PAWN scripting skills or basic problem solving skills
then please do post on forum.sa-mp.com for help or hire a scripter that
will do this for you.
