### ISSUE TITLE
GPS RouteConnector Issues

### ISSUE THREAD

**Issue by Abyss-z94** [grasmanek94/GPB#6]
I got problem when runin RouteConnectorPlugin.so on CentOS 7

That warning: Failed (/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by plugins/RouteConnectorPlugin.so))

but in my vps have been installed libstdc++.so.6 include GLIBCXX_3.4.20, what should i do now ?

> [root@static GvC-RP]# strings /usr/lib64/libstdc++.so.6 | grep GLIBC
> GLIBCXX_3.4
> GLIBCXX_3.4.1
> GLIBCXX_3.4.2
> GLIBCXX_3.4.3
> GLIBCXX_3.4.4
> GLIBCXX_3.4.5
> GLIBCXX_3.4.6
> GLIBCXX_3.4.7
> GLIBCXX_3.4.8
> GLIBCXX_3.4.9
> GLIBCXX_3.4.10
> GLIBCXX_3.4.11
> GLIBCXX_3.4.12
> GLIBCXX_3.4.13
> GLIBCXX_3.4.14
> GLIBCXX_3.4.15
> GLIBCXX_3.4.16
> GLIBCXX_3.4.17
> GLIBCXX_3.4.18
> GLIBCXX_3.4.19
> GLIBCXX_3.4.20
> GLIBC_2.3
> GLIBC_2.2.5
> GLIBC_2.14
> GLIBC_2.17
> GLIBC_2.3.2
> GLIBCXX_DEBUG_MESSAGE_LENGTH
> __strtof_l@@GLIBC_2.2.5
> _ZNKSt14basic_ifstreamIcSt11char_traitsIcEE7is_openEv@GLIBCXX_3.4
> fileno@@GLIBC_2.2.5
> pthread_cond_destroy@@GLIBC_2.3.2
> __strcoll_l@@GLIBC_2.2.5
> __nl_langinfo_l@@GLIBC_2.2.5
> fseeko64@@GLIBC_2.2.5
> wmemcpy@@GLIBC_2.2.5
> memset@@GLIBC_2.2.5
> mbrtowc@@GLIBC_2.2.5
> _ZNSt13basic_istreamIwSt11char_traitsIwEE6ignoreEv@@GLIBCXX_3.4.5
> snprintf@@GLIBC_2.2.5
> wcslen@@GLIBC_2.2.5
> __duplocale@@GLIBC_2.2.5
> ceil@@GLIBC_2.2.5
> ioctl@@GLIBC_2.2.5
> abort@@GLIBC_2.2.5
> memchr@@GLIBC_2.2.5
> _ZNKSbIwSt11char_traitsIwESaIwEE11_M_disjunctEPKw@GLIBCXX_3.4
> _ZNKSt14basic_ifstreamIwSt11char_traitsIwEE7is_openEv@@GLIBCXX_3.4.5
> clock_gettime@@GLIBC_2.17
> pthread_cond_signal@@GLIBC_2.3.2
> textdomain@@GLIBC_2.2.5
> GLIBCXX_3.4.5
> __assert_fail@@GLIBC_2.2.5
> GLIBCXX_3.4.9
> _ZSt10adopt_lock@@GLIBCXX_3.4.11
> GLIBCXX_3.4.10
> bindtextdomain@@GLIBC_2.2.5
> wmemcmp@@GLIBC_2.2.5
> __strftime_l@@GLIBC_2.3
> gettimeofday@@GLIBC_2.2.5
> GLIBCXX_3.4.16
> setvbuf@@GLIBC_2.2.5
> __strxfrm_l@@GLIBC_2.2.5
> GLIBCXX_3.4.1
> _ZNSt19istreambuf_iteratorIcSt11char_traitsIcEEppEv@GLIBCXX_3.4
> _ZNSs7_M_copyEPcPKcm@GLIBCXX_3.4
> mbsnrtowcs@@GLIBC_2.2.5
> read@@GLIBC_2.2.5
> malloc@@GLIBC_2.2.5
> fopen@@GLIBC_2.2.5
> gettext@@GLIBC_2.2.5
> strtold_l@@GLIBC_2.3
> _ZNSt19istreambuf_iteratorIcSt11char_traitsIcEEppEv@@GLIBCXX_3.4.5
> _ZNSs7_M_moveEPcPKcm@@GLIBCXX_3.4.5
> _ZNKSt13basic_fstreamIwSt11char_traitsIwEE7is_openEv@GLIBCXX_3.4
> ungetwc@@GLIBC_2.2.5
> __wctype_l@@GLIBC_2.2.5
> __cxa_atexit@@GLIBC_2.2.5
> _ZNKSt13basic_fstreamIcSt11char_traitsIcEE7is_openEv@GLIBCXX_3.4
> _ZNSbIwSt11char_traitsIwESaIwEE4_Rep26_M_set_length_and_sharableEm@@GLIBCXX_3.4.5
> _ZNSs4_Rep26_M_set_length_and_sharableEm@GLIBCXX_3.4
> _ZSt10defer_lock@@GLIBCXX_3.4.11
> __towupper_l@@GLIBC_2.2.5
> __wcsxfrm_l@@GLIBC_2.2.5
> __fxstat64@@GLIBC_2.2.5
> _ZN10__gnu_norm15_List_node_base4swapERS0_S1_@@GLIBCXX_3.4
> _ZNSs9_M_assignEPcmc@@GLIBCXX_3.4.5
> ungetc@@GLIBC_2.2.5
> _ZNKSbIwSt11char_traitsIwESaIwEE15_M_check_lengthEmmPKc@@GLIBCXX_3.4.5
> __wcscoll_l@@GLIBC_2.2.5
> fputc@@GLIBC_2.2.5
> _ZNKSt14basic_ifstreamIcSt11char_traitsIcEE7is_openEv@@GLIBCXX_3.4.5
> free@@GLIBC_2.2.5
> _ZNSbIwSt11char_traitsIwESaIwEE7_M_moveEPwPKwm@GLIBCXX_3.4
> strlen@@GLIBC_2.2.5
> _ZNVSt9__atomic011atomic_flag12test_and_setESt12memory_order@@GLIBCXX_3.4.11
> GLIBCXX_3.4.20
> wmemchr@@GLIBC_2.2.5
> _ZNSt11char_traitsIwE2eqERKwS2_@@GLIBCXX_3.4.5
> GLIBCXX_3.4.12
> _ZNSi6ignoreEv@@GLIBCXX_3.4.5
> __ctype_get_mb_cur_max@@GLIBC_2.2.5
> GLIBCXX_3.4.2
> __cxa_finalize@@GLIBC_2.2.5
> _ZNSt11char_traitsIcE2eqERKcS2_@@GLIBCXX_3.4.5
> GLIBCXX_3.4.6
> wctob@@GLIBC_2.2.5
> __wcsftime_l@@GLIBC_2.3
> __iswctype_l@@GLIBC_2.2.5
> GLIBCXX_3.4.15
> __tls_get_addr@@GLIBC_2.3
> sprintf@@GLIBC_2.2.5
> _ZNKSt13basic_fstreamIcSt11char_traitsIcEE7is_openEv@@GLIBCXX_3.4.5
> stdin@@GLIBC_2.2.5
> _ZNSs9_M_assignEPcmc@GLIBCXX_3.4
> GLIBCXX_3.4.19
> _ZNKSt14basic_ofstreamIwSt11char_traitsIwEE7is_openEv@GLIBCXX_3.4
> _ZNSt19istreambuf_iteratorIwSt11char_traitsIwEEppEv@GLIBCXX_3.4
> fdopen@@GLIBC_2.2.5
> syscall@@GLIBC_2.2.5
> _ZN10__gnu_norm15_List_node_base7reverseEv@@GLIBCXX_3.4
> __newlocale@@GLIBC_2.2.5
> poll@@GLIBC_2.2.5
> frexpl@@GLIBC_2.2.5
> strerror@@GLIBC_2.2.5
> fputs@@GLIBC_2.2.5
> mbsrtowcs@@GLIBC_2.2.5
> _ZN10__gnu_norm15_List_node_base4hookEPS0_@@GLIBCXX_3.4
> wcrtomb@@GLIBC_2.2.5
> putwc@@GLIBC_2.2.5
> _ZNSt11char_traitsIwE2eqERKwS2_@GLIBCXX_3.4
> _ZNSbIwSt11char_traitsIwESaIwEE7_M_copyEPwPKwm@GLIBCXX_3.4
> putc@@GLIBC_2.2.5
> _ZNSbIwSt11char_traitsIwESaIwEE7_M_copyEPwPKwm@@GLIBCXX_3.4.5
> memmove@@GLIBC_2.2.5
> strchr@@GLIBC_2.2.5
> vsnprintf@@GLIBC_2.2.5
> fread@@GLIBC_2.2.5
> wmemmove@@GLIBC_2.2.5
> getenv@@GLIBC_2.2.5
> GLIBCXX_3.4.11
> GLIBCXX_3.4.3
> GLIBCXX_3.4.7
> __errno_location@@GLIBC_2.2.5
> _ZNSi6ignoreEl@@GLIBCXX_3.4.5
> _ZNKSbIwSt11char_traitsIwESaIwEE11_M_disjunctEPKw@@GLIBCXX_3.4.5
> _ZNSt13basic_istreamIwSt11char_traitsIwEE6ignoreEv@GLIBCXX_3.4
> _ZNKSt13basic_fstreamIwSt11char_traitsIwEE7is_openEv@@GLIBCXX_3.4.5
> GLIBCXX_3.4.14
> _ZNSbIwSt11char_traitsIwESaIwEE7_M_moveEPwPKwm@@GLIBCXX_3.4.5
> __uselocale@@GLIBC_2.3
> GLIBCXX_3.4.18
> _ZNSbIwSt11char_traitsIwESaIwEE4_Rep26_M_set_length_and_sharableEm@GLIBCXX_3.4
> _ZNSt13basic_istreamIwSt11char_traitsIwEE6ignoreEl@@GLIBCXX_3.4.5
> strcmp@@GLIBC_2.2.5
> _ZSt15future_category@@GLIBCXX_3.4.14
> _ZNSi6ignoreEl@GLIBCXX_3.4
> get_nprocs@@GLIBC_2.2.5
> GLIBCXX_3.4
> __strtod_l@@GLIBC_2.2.5
> getwc@@GLIBC_2.2.5
> nanosleep@@GLIBC_2.2.5
> pthread_cond_wait@@GLIBC_2.3.2
> _ZNSt11char_traitsIcE2eqERKcS2_@GLIBCXX_3.4
> _ZNKSs15_M_check_lengthEmmPKc@GLIBCXX_3.4
> _ZN10__gnu_norm15_List_node_base8transferEPS0_S1_@@GLIBCXX_3.4
> memcmp@@GLIBC_2.2.5
> _ZNSbIwSt11char_traitsIwESaIwEE9_M_assignEPwmw@GLIBCXX_3.4
> writev@@GLIBC_2.2.5
> _ZNVSt9__atomic011atomic_flag5clearESt12memory_order@@GLIBCXX_3.4.11
> fclose@@GLIBC_2.2.5
> _ZNKSt14basic_ofstreamIcSt11char_traitsIcEE7is_openEv@@GLIBCXX_3.4.5
> isalnum@@GLIBC_2.2.5
> _ZNKSt14basic_ofstreamIcSt11char_traitsIcEE7is_openEv@GLIBCXX_3.4
> _ZNSs7_M_moveEPcPKcm@GLIBCXX_3.4
> isspace@@GLIBC_2.2.5
> lseek64@@GLIBC_2.2.5
> __freelocale@@GLIBC_2.2.5
> _ZNSt13basic_istreamIwSt11char_traitsIwEE6ignoreEl@GLIBCXX_3.4
> wcsnrtombs@@GLIBC_2.2.5
> _ZNSbIwSt11char_traitsIwESaIwEE9_M_assignEPwmw@@GLIBCXX_3.4.5
> stderr@@GLIBC_2.2.5
> btowc@@GLIBC_2.2.5
> _ZNKSbIwSt11char_traitsIwESaIwEE15_M_check_lengthEmmPKc@GLIBCXX_3.4
> _ZNKSs11_M_disjunctEPKc@@GLIBCXX_3.4.5
> _ZN10__gnu_norm15_List_node_base6unhookEv@@GLIBCXX_3.4
> fopen64@@GLIBC_2.2.5
> _ZNSt19istreambuf_iteratorIwSt11char_traitsIwEEppEv@@GLIBCXX_3.4.5
> _ZNSi6ignoreEv@GLIBCXX_3.4
> wcscmp@@GLIBC_2.2.5
> fwrite@@GLIBC_2.2.5
> pthread_mutex_lock@@GLIBC_2.2.5
> _ZNSs7_M_copyEPcPKcm@@GLIBCXX_3.4.5
> realloc@@GLIBC_2.2.5
> setlocale@@GLIBC_2.2.5
> floor@@GLIBC_2.2.5
> GLIBCXX_3.4.8
> GLIBCXX_3.4.13
> _ZSt11try_to_lock@@GLIBCXX_3.4.11
> write@@GLIBC_2.2.5
> _ZNKSt14basic_ofstreamIwSt11char_traitsIwEE7is_openEv@@GLIBCXX_3.4.5
> pthread_cond_broadcast@@GLIBC_2.3.2
> GLIBCXX_3.4.17
> GLIBCXX_3.4.4
> ftello64@@GLIBC_2.2.5
> _ZNKSs15_M_check_lengthEmmPKc@@GLIBCXX_3.4.5
> strtoul@@GLIBC_2.2.5
> pthread_mutex_unlock@@GLIBC_2.2.5
> memcpy@@GLIBC_2.14
> _ZNKSt14basic_ifstreamIwSt11char_traitsIwEE7is_openEv@GLIBCXX_3.4
> __towlower_l@@GLIBC_2.2.5
> _ZNSs4_Rep26_M_set_length_and_sharableEm@@GLIBCXX_3.4.5
> stdout@@GLIBC_2.2.5
> _ZNKSs11_M_disjunctEPKc@GLIBCXX_3.4
> wmemset@@GLIBC_2.2.5
> fflush@@GLIBC_2.2.5
> getc@@GLIBC_2.2.5
> [root@static GvC-RP]#
>

**Comment by grasmanek94** [comment]
I know it's a tedious process because of libtbb.... but could you try recompiling the plugin on that particular VPS, please?

I think your VPS has a 64-bit based OS, SA-MP and all it's dependencies and plugins require x86 binaries/libraries, which is why you should install the i686 architecture of glibc/glibcxx onto your system.

Try
yum install glibc.i686

You could also try the steps mentioned in [this](https://serverfault.com/questions/512788/how-to-install-32-bit-packages-on-a-64-bit-centos) serverfault post.

**Comment by Abyss-z94** [comment]
[root@static ~]# yum install glibc.i686
Loaded plugins: fastestmirror
base                                                     | 3.6 kB     00:00
epel/x86_64/metalink                                     | 5.5 kB     00:00
epel                                                     | 4.3 kB     00:00
extras                                                   | 3.4 kB     00:00
mysql-connectors-community                               | 2.5 kB     00:00
mysql-tools-community                                    | 2.5 kB     00:00
mysql56-community                                        | 2.5 kB     00:00
updates                                                  | 3.4 kB     00:00
(1/3): epel/x86_64/updateinfo                              | 759 kB   00:00
(2/3): updates/7/x86_64/primary_db                         | 3.8 MB   00:00
(3/3): epel/x86_64/primary_db                              | 4.6 MB   00:01
Loading mirror speeds from cached hostfile
 * base: mirrors.nhanhoa.com
 * epel: mirrors.digipower.vn
 * extras: mirrors.nhanhoa.com
 * updates: mirrors.nhanhoa.com
Package glibc-2.17-157.el7_3.1.i686 already installed and latest version
Nothing to do
[root@static ~]#

That glibc.i686 has been installed on my vps already.

**Comment by Abyss-z94** [comment]
How to recompiling plugins mate? I have no idea about this.

**Comment by grasmanek94** [comment]
after you setup the development utilities / GNU Compiler Collection and libraries on your linux distribution (According to the documentation of your linux distribution, for example: on debian this is `build-essential`), `cd` to the source directory and type `make RouteConnectorPlugin`. There should be no errors and no warnings. After that the binary will exist in the top-level folder.

Make sure that you install the x86 tools / libraries too. On debian x64 the extra needed packages for x86 development (and C and C++ runtime) are `libc6-dev-i386 gcc-multilib g++-multilib` (please find the equivalent packages for your OS)

Make sure that you have the x86 libtbb2 runtime installed too, on debian x64 this is the package `libtbb2:i386`

On a x86 OS you can omit the last two steps and instead just make sure your OS has the libtbb2 runtime available by installing the equivalent (to debian x86) `libtbb2` package.

I have confirmed and tested (sa-mp 0.3.7 server) all the above information on a clean Debian 8.7 x64 install.
